# Site settings
client: Consumer Reports
title: Digital Standard
email: dev@ocupop.com
url: "https://ocupop.github.io"
permalink: pretty

# Social sharing
description: The Digital Standard is a framework to evaluate consumer technologies and how they respect people’s interests and needs.
socialshare:
  featured_image:
  twitter:
    username:
    image:

# Google Analytics
analytics:
  default:


# Collections
collections:
  examples:
    output: true
    permalink: /examples/:path/

defaults:
  -
    scope:
      type: 'examples'
    values:
      layout: example
      # variable_name: value

# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss
plugins:
  - jekyll-sitemap

placeholder_image: https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder

